name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Caprover deploy
      uses: AlexxNB/caprover-action@v1
      with:
        server: 'https://captain.paas.drackmord.space'
        password: '${{ secrets.CAPROVER_PASSWORD }}'
        appname: 'bot-test'
