on: push
name: 🚀 Deploy bot on push
jobs:
  bot-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Set secrets
      run: |
        sed -i'.backup' -e 's/BOT_TOKEN =.*$/BOT_TOKEN = "cacca"/' modules/config.py
        sed -i'.backup' -e 's/DB_CONNECTION_URL =.*$/DB_CONNECTION_URL = "cacca"/' modules/config.py
        sed -i'.backup' -e 's/DB_NAME =.*$/DB_NAME = "${{ secrets.DB_NAME }}"/' modules/config.py

    - name: 📂 Sync files
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: '${{ secrets.HOST_IP }}'
        port: ${{ secrets.HOST_PORT }}
        username: '${{ secrets.HOST_USER }}'
        password: '${{ secrets.HOST_PASSWORD }}'
        localPath: '.'
        remotePath: '/'
